const dbConnection = require("../mongoConnection");
const data = require("../data/");
const books = data.book;

async function main() {
  const db = await dbConnection();
  await db.dropDatabase();

  const harry1 = await books.create("Harry Potter And The Sorcerer's Stone", "J.K. Rowling","Scholastic Press","Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry. Harry makes close friends and a few enemies during his first year at the school, and with the help of his friends, Harry faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old.",["Fiction", "Fanasy","Drama","Thriller"],"3.79","0-7475-3009-9","uploads/harry1.png","Used Book","English","1998-08-31","HARRY POTTER");
  const harry2 = await books.create("Harry Potter And The Sorcerer's Stone", "J.K. Rowling","Scholastic Press","Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry. Harry makes close friends and a few enemies during his first year at the school, and with the help of his friends, Harry faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old.",["Fiction", "Fanasy","Drama","Thriller"],"3.79","0-7475-3010-9","uploads/harry1.png","Used Book","English","1998-08-31","HARRY POTTER");
  const harry3 = await books.create("Harry Potter And The Sorcerer's Stone", "J.K. Rowling","Scholastic Press","Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry. Harry makes close friends and a few enemies during his first year at the school, and with the help of his friends, Harry faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old.",["Fiction", "Fanasy","Drama","Thriller"],"3.79","0-7475-3011-9","uploads/harry1.png","Used Book","English","1998-08-31","HARRY POTTER");
  const harry4 = await books.create("Harry Potter And The Sorcerer's Stone", "J.K. Rowling","Scholastic Press","Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry. Harry makes close friends and a few enemies during his first year at the school, and with the help of his friends, Harry faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old.",["Fiction", "Fanasy","Drama","Thriller"],"3.79","0-7475-3012-9","uploads/harry1.png","Used Book","English","1998-08-31","HARRY POTTER");
  const harry5 = await books.create("Harry Potter And The Sorcerer's Stone", "J.K. Rowling","Scholastic Press","Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry. Harry makes close friends and a few enemies during his first year at the school, and with the help of his friends, Harry faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old.",["Fiction", "Fanasy","Drama","Thriller"],"3.79","0-7475-3013-9","uploads/harry1.png","Used Book","English","1998-08-31","HARRY POTTER");
  const harry6 = await books.create("Harry Potter And The Sorcerer's Stone", "J.K. Rowling","Scholastic Press","Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry. Harry makes close friends and a few enemies during his first year at the school, and with the help of his friends, Harry faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old.",["Fiction", "Fanasy","Drama","Thriller"],"3.79","0-7475-3014-9","uploads/harry1.png","Used Book","English","1998-08-31","HARRY POTTER");
  const harry7 = await books.create("Harry Potter And The Sorcerer's Stone", "J.K. Rowling","Scholastic Press","Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry. Harry makes close friends and a few enemies during his first year at the school, and with the help of his friends, Harry faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old.",["Fiction", "Fanasy","Drama","Thriller"],"3.79","0-7475-3015-9","uploads/harry1.png","Used Book","English","1998-08-31","HARRY POTTER");

  const nightside1 = await books.create("Paths not Taken", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Fiction", "Fanasy","Drama","Thriller"],"10.79","0-441-01319-4","uploads/night1.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const nightside2 = await books.create("Paths not Taken", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Fiction", "Fanasy","Drama","Thriller"],"10.79","0-441-01319-5","uploads/night1.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const nightside3 = await books.create("Paths not Taken", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Fiction", "Fanasy","Drama","Thriller"],"10.79","0-441-01319-6","uploads/night1.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const nightside4 = await books.create("Paths not Taken", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Fiction", "Fanasy","Drama","Thriller"],"10.79","0-441-01319-7","uploads/night1.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const nightside5 = await books.create("Paths not Taken", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Fiction", "Fanasy","Drama","Thriller"],"10.79","0-441-01319-8","uploads/night1.png","Used Book","English","2005-08-30","NIGHTSIDE");

  console.log("Done seeding database");
  await db.close();
}

main();